// generated by src/lib/package.gen.ts

import type {Package_Json} from '@grogarden/gro/package_json.js';

import type {Src_Json} from '@grogarden/gro/src_json.js';

export const package_json = {
	name: '@fuz.dev/fuz_contextmenu',
	description: 'contextmenu for Svelte and Fuz',
	version: '0.6.0',
	public: true,
	type: 'module',
	license: 'MIT',
	homepage: 'https://contextmenu.fuz.dev/',
	repository: 'https://github.com/fuz-dev/fuz_contextmenu',
	author: {name: 'Ryan Atkinson', email: 'mail@ryanatkn.com', url: 'https://www.ryanatkn.com/'},
	engines: {node: '>=20.7'},
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		test: 'gro test',
		deploy: 'gro deploy',
	},
	files: ['dist'],
	peerDependencies: {'@fuz.dev/fuz_library': '*', '@grogarden/util': '*', svelte: '*'},
	devDependencies: {
		'@changesets/changelog-git': '^0.1.14',
		'@feltjs/eslint-config': '^0.4.1',
		'@fuz.dev/fuz': '^0.79.3',
		'@fuz.dev/fuz_code': '^0.4.3',
		'@fuz.dev/fuz_dialog': '^0.5.0',
		'@fuz.dev/fuz_library': '^0.21.0',
		'@grogarden/gro': '^0.102.0',
		'@grogarden/util': '^0.16.0',
		'@sveltejs/adapter-static': '^2.0.3',
		'@sveltejs/kit': '^1.27.3',
		'@sveltejs/package': '^2.2.2',
		'@types/prismjs': '^1.26.3',
		'@typescript-eslint/eslint-plugin': '^6.10.0',
		'@typescript-eslint/parser': '^6.10.0',
		eslint: '^8.53.0',
		'eslint-plugin-svelte': '^2.35.0',
		prettier: '^3.0.3',
		'prettier-plugin-svelte': '^3.0.3',
		'prism-svelte': '^0.5.0',
		prismjs: '^1.29.0',
		svelte: '^4.2.2',
		'svelte-check': '^3.5.2',
		tslib: '^2.6.2',
		typescript: '^5.2.2',
		uvu: '^0.5.6',
	},
	eslintConfig: {root: true, extends: '@feltjs'},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	exports: {
		'./Contextmenu_Entry.svelte': {
			svelte: './dist/Contextmenu_Entry.svelte',
			default: './dist/Contextmenu_Entry.svelte',
			types: './dist/Contextmenu_Entry.svelte.d.ts',
		},
		'./Contextmenu_Link_Entry.svelte': {
			svelte: './dist/Contextmenu_Link_Entry.svelte',
			default: './dist/Contextmenu_Link_Entry.svelte',
			types: './dist/Contextmenu_Link_Entry.svelte.d.ts',
		},
		'./Contextmenu_Submenu.svelte': {
			svelte: './dist/Contextmenu_Submenu.svelte',
			default: './dist/Contextmenu_Submenu.svelte',
			types: './dist/Contextmenu_Submenu.svelte.d.ts',
		},
		'./Contextmenu_Text_Entry.svelte': {
			svelte: './dist/Contextmenu_Text_Entry.svelte',
			default: './dist/Contextmenu_Text_Entry.svelte',
			types: './dist/Contextmenu_Text_Entry.svelte.d.ts',
		},
		'./Contextmenu.svelte': {
			svelte: './dist/Contextmenu.svelte',
			default: './dist/Contextmenu.svelte',
			types: './dist/Contextmenu.svelte.d.ts',
		},
		'./contextmenu.js': {default: './dist/contextmenu.js', types: './dist/contextmenu.d.ts'},
		'./package.gen.js': {default: './dist/package.gen.js', types: './dist/package.gen.d.ts'},
		'./package.js': {default: './dist/package.js', types: './dist/package.d.ts'},
	},
} satisfies Package_Json;

export const src_json = {
	name: '@fuz.dev/fuz_contextmenu',
	version: '0.6.0',
	modules: {
		'./Contextmenu_Entry.svelte': {path: 'Contextmenu_Entry.svelte', declarations: []},
		'./Contextmenu_Link_Entry.svelte': {path: 'Contextmenu_Link_Entry.svelte', declarations: []},
		'./Contextmenu_Submenu.svelte': {path: 'Contextmenu_Submenu.svelte', declarations: []},
		'./Contextmenu_Text_Entry.svelte': {path: 'Contextmenu_Text_Entry.svelte', declarations: []},
		'./Contextmenu.svelte': {path: 'Contextmenu.svelte', declarations: []},
		'./contextmenu.js': {
			path: 'contextmenu.ts',
			declarations: [
				{name: 'Contextmenu_Params', kind: 'type'},
				{name: 'Contextmenu_Action_Params', kind: 'type'},
				{name: 'to_contextmenu_params', kind: 'function'},
				{name: 'Item_State', kind: 'type'},
				{name: 'Entry_State', kind: 'type'},
				{name: 'Submenu_State', kind: 'type'},
				{name: 'Root_Menu_State', kind: 'type'},
				{name: 'Contextmenu_Run', kind: 'type'},
				{name: 'Contextmenu', kind: 'type'},
				{name: 'Contextmenu_Store', kind: 'type'},
				{name: 'Contextmenu_Store_Options', kind: 'type'},
				{name: 'create_contextmenu', kind: 'function'},
				{name: 'open_contextmenu', kind: 'function'},
				{name: 'set_contextmenu', kind: 'function'},
				{name: 'get_contextmenu', kind: 'function'},
				{name: 'set_contextmenu_submenu', kind: 'function'},
				{name: 'get_contextmenu_submenu', kind: 'function'},
				{name: 'set_contextmenu_dimensions', kind: 'function'},
				{name: 'get_contextmenu_dimensions', kind: 'function'},
			],
		},
		'./package.gen.js': {path: 'package.gen.ts', declarations: []},
		'./package.js': {
			path: 'package.ts',
			declarations: [
				{name: 'package_json', kind: 'variable'},
				{name: 'src_json', kind: 'variable'},
			],
		},
	},
} satisfies Src_Json;

// generated by src/lib/package.gen.ts
